import argparse, csv, json, math, os, random, sqlite3
from datetime import date, datetime, time, timedelta
from pathlib import Path

parser = argparse.ArgumentParser()
parser.add_argument("--seed",    type=int, default=42)
parser.add_argument("--db",      default="mindy_world.db")
parser.add_argument("--csv-dir", default="csvs_world")
args = parser.parse_args()
random.seed(args.seed)
Path(args.csv_dir).mkdir(exist_ok=True)

# assistance from the following 2 sources for help writing sql queries to mass insert data:
# https://stackoverflow.com/questions/13020908/sql-multiple-inserts-with-python
# https://www.geeksforgeeks.org/python/insert-multiple-rows-in-mysql-table-in-python/
# individual data points for airports, hotels, etc and large sql queries/calculation logic were mass generated by AI chatbot to avoid manual data entry for thousands of items

AIRPORTS = [
    ("JFK","New York","NY",-5,40.64,-73.78),
    ("LAX","Los Angeles","CA",-8,33.94,-118.41),
    ("ORD","Chicago","IL",-6,41.98,-87.91),
    ("DFW","Dallas","TX",-6,32.90,-97.04),
    ("ATL","Atlanta","GA",-5,33.64,-84.43),
    ("SFO","San Francisco","CA",-8,37.62,-122.38),
    ("SEA","Seattle","WA",-8,47.45,-122.31),
    ("MIA","Miami","FL",-5,25.80,-80.29),
    ("BOS","Boston","MA",-5,42.36,-71.01),
    ("DEN","Denver","CO",-7,39.86,-104.67),
    ("LAS","Las Vegas","NV",-8,36.08,-115.15),
    ("PHX","Phoenix","AZ",-7,33.44,-112.01),
    ("MSP","Minneapolis","MN",-6,44.88,-93.22),
    ("DTW","Detroit","MI",-5,42.21,-83.35),
    ("PDX","Portland","OR",-8,45.59,-122.60),
    ("SAN","San Diego","CA",-8,32.73,-117.19),
    ("AUS","Austin","TX",-6,30.20,-97.67),
    ("BNA","Nashville","TN",-6,36.12,-86.68),
    ("CLE","Cleveland","OH",-5,41.41,-81.85),
    ("MSY","New Orleans","LA",-6,29.99,-90.26),
    ("SLC","Salt Lake City","UT",-7,40.79,-111.98),
    ("IAH","Houston","TX",-6,29.99,-95.34),
    ("PHL","Philadelphia","PA",-5,39.87,-75.24),
    ("BWI","Baltimore","MD",-5,39.18,-76.67),
    ("DCA","Washington DC","VA",-5,38.85,-77.04),
    ("RDU","Raleigh","NC",-5,35.88,-78.79),
    ("TPA","Tampa","FL",-5,27.98,-82.53),
    ("MCO","Orlando","FL",-5,28.43,-81.31),
    ("STL","St. Louis","MO",-6,38.75,-90.37),
    ("MCI","Kansas City","MO",-6,39.30,-94.71),
    ("IND","Indianapolis","IN",-5,39.72,-86.29),
    ("CMH","Columbus","OH",-5,39.99,-82.89),
    ("PIT","Pittsburgh","PA",-5,40.49,-80.23),
    ("MKE","Milwaukee","WI",-6,42.95,-87.90),
    ("OMA","Omaha","NE",-6,41.30,-95.89),
    ("ABQ","Albuquerque","NM",-7,35.04,-106.61),
    ("TUL","Tulsa","OK",-6,36.20,-95.89),
    ("OKC","Oklahoma City","OK",-6,35.39,-97.60),
    ("ELP","El Paso","TX",-7,31.81,-106.38),
    ("LIT","Little Rock","AR",-6,34.73,-92.22),
    ("MEM","Memphis","TN",-6,35.04,-89.98),
    ("BHM","Birmingham","AL",-6,33.56,-86.75),
    ("JAX","Jacksonville","FL",-5,30.49,-81.69),
    ("SAV","Savannah","GA",-5,32.13,-81.20),
    ("CHS","Charleston","SC",-5,32.90,-80.04),
    ("BOI","Boise","ID",-7,43.56,-116.22),
    ("GEG","Spokane","WA",-8,47.62,-117.53),
    ("FAT","Fresno","CA",-8,36.78,-119.72),
    ("SMF","Sacramento","CA",-8,38.70,-121.59),
    ("ONT","Ontario","CA",-8,34.06,-117.60),
]

AIRPORT_LOOKUP = {r[0]: r for r in AIRPORTS}

AIRLINES = [
    ("AA","American Airlines",  0.82,0.015),
    ("DL","Delta Air Lines",    0.87,0.010),
    ("UA","United Airlines",    0.80,0.018),
    ("WN","Southwest Airlines", 0.78,0.020),
    ("B6","JetBlue Airways",    0.75,0.022),
    ("AS","Alaska Airlines",    0.85,0.012),
    ("F9","Frontier Airlines",  0.72,0.025),
    ("NK","Spirit Airlines",    0.68,0.030),
    ("G4","Allegiant Air",      0.70,0.028),
    ("SY","Sun Country",        0.76,0.021),
]

HOTEL_CHAINS = [
    ("Marriott",         "luxury",   (200,450), ["pool","gym","spa","restaurant","wifi","parking","bar","concierge"]),
    ("Ritz-Carlton",     "luxury",   (350,700), ["pool","gym","spa","restaurant","wifi","parking","bar","concierge","valet"]),
    ("W Hotels",         "luxury",   (280,550), ["pool","gym","spa","restaurant","wifi","bar","rooftop"]),
    ("Westin",           "luxury",   (220,480), ["pool","gym","spa","restaurant","wifi","parking"]),
    ("Hilton",           "upscale",  (150,350), ["pool","gym","restaurant","wifi","parking","bar"]),
    ("Hyatt Regency",    "upscale",  (160,380), ["pool","gym","spa","restaurant","wifi","bar"]),
    ("Sheraton",         "upscale",  (140,320), ["pool","gym","restaurant","wifi","parking"]),
    ("Kimpton",          "upscale",  (170,360), ["gym","restaurant","wifi","bar","pet_friendly"]),
    ("Renaissance",      "upscale",  (155,340), ["pool","gym","restaurant","wifi","parking"]),
    ("Crowne Plaza",     "upscale",  (130,300), ["pool","gym","restaurant","wifi","parking","breakfast"]),
    ("Holiday Inn",      "midscale", (90,180),  ["pool","gym","wifi","breakfast","parking"]),
    ("Hampton Inn",      "midscale", (80,160),  ["pool","gym","wifi","breakfast"]),
    ("Courtyard",        "midscale", (95,190),  ["pool","gym","wifi","parking"]),
    ("Fairfield Inn",    "midscale", (75,150),  ["pool","gym","wifi","breakfast"]),
    ("Comfort Inn",      "midscale", (70,145),  ["pool","wifi","breakfast"]),
    ("Best Western",     "midscale", (75,155),  ["pool","wifi","breakfast","parking"]),
    ("Radisson",         "midscale", (100,200), ["pool","gym","restaurant","wifi","parking"]),
    ("DoubleTree",       "midscale", (110,220), ["pool","gym","wifi","parking","bar"]),
    ("La Quinta",        "economy",  (60,120),  ["pool","wifi","breakfast"]),
    ("Motel 6",          "economy",  (40,80),   ["wifi","parking"]),
    ("Super 8",          "economy",  (45,85),   ["wifi","breakfast"]),
    ("Days Inn",         "economy",  (50,95),   ["pool","wifi","breakfast"]),
    ("Travelodge",       "economy",  (45,90),   ["wifi","parking"]),
    ("Extended Stay",    "economy",  (55,110),  ["wifi","kitchen","parking"]),
    ("Airbnb Entire",    "midscale", (70,250),  ["wifi","kitchen","washer","parking"]),
    ("Boutique Hotel",   "upscale",  (130,300), ["gym","restaurant","wifi","bar"]),
    ("Autograph Coll.",  "upscale",  (160,370), ["pool","gym","restaurant","wifi","bar","spa"]),
    ("Tapestry Coll.",   "midscale", (100,210), ["pool","gym","wifi","restaurant"]),
]

ACTIVITY_TEMPLATES = [
    ("{city} Art Museum",              "culture",      3.0, (15,  35), ["art","indoor","family","culture"]),
    ("{city} History Museum",          "culture",      2.5, (12,  28), ["history","indoor","family","culture"]),
    ("{city} Natural History Museum",  "culture",      3.0, (14,  30), ["history","indoor","family","education"]),
    ("{city} Contemporary Art Gall.",  "culture",      2.0, (10,  25), ["art","indoor","adults","culture"]),
    ("Downtown {city} Food Tour",      "food",         3.0, (55,  95), ["food","walking","adults"]),
    ("{city} Street Food Walk",        "food",         2.5, (35,  70), ["food","walking","adults","outdoor"]),
    ("{city} Craft Beer Tour",         "food",         3.0, (45,  85), ["food","adults","indoor","nightlife"]),
    ("{city} Wine & Cheese Tasting",   "food",         2.5, (50,  90), ["food","adults","indoor"]),
    ("{city} Cooking Class",           "food",         3.5, (75, 130), ["food","indoor","adults"]),
    ("Vegan Food Tour {city}",         "food",         3.0, (50,  90), ["food","vegan","walking","adults"]),
    ("{city} Farmers Market",          "food",         2.0, (0,   20), ["food","outdoor","morning","family"]),
    ("{city} Coffee Roastery Tour",    "food",         1.5, (20,  40), ["food","indoor","adults","morning"]),
    ("{city} Botanical Garden",        "nature",       2.0, (10,  25), ["nature","outdoor","family"]),
    ("{city} Zoo",                     "nature",       4.0, (20,  40), ["nature","outdoor","family"]),
    ("{city} Aquarium",                "nature",       3.0, (25,  45), ["nature","indoor","family"]),
    ("{city} State Park Hike",         "adventure",    4.0, (0,   15), ["outdoor","active","nature","adventure"]),
    ("{city} Waterfall Trail",         "adventure",    3.5, (0,   10), ["outdoor","active","nature","adventure"]),
    ("Kayaking in {city}",             "adventure",    3.0, (40,  80), ["water","outdoor","active","adventure"]),
    ("{city} Bike Tour",               "adventure",    3.0, (35,  65), ["outdoor","active","adults","adventure"]),
    ("{city} Rock Climbing",           "adventure",    3.5, (55,  95), ["outdoor","active","adults","adventure"]),
    ("Sunset Sailing {city}",          "sightseeing",  2.5, (55,  95), ["water","outdoor","scenic","adults"]),
    ("Harbor Cruise {city}",           "sightseeing",  2.0, (30,  60), ["water","outdoor","scenic","family"]),
    ("{city} Helicopter Tour",         "sightseeing",  1.0, (100,200), ["aerial","outdoor","scenic","adults"]),
    ("Architecture Walk {city}",       "culture",      2.0, (0,   25), ["walking","outdoor","history","culture"]),
    ("Street Art Tour {city}",         "culture",      2.0, (0,   30), ["outdoor","walking","art","culture"]),
    ("{city} Neighborhood Tour",       "culture",      2.5, (20,  45), ["walking","outdoor","history","culture"]),
    ("Sunset Rooftop Bar {city}",      "nightlife",    2.0, (20,  50), ["nightlife","adults","views","bar"]),
    ("{city} Jazz Club",               "nightlife",    2.5, (20,  50), ["music","adults","evening","nightlife"]),
    ("{city} Comedy Club",             "entertainment",2.0, (25,  55), ["nightlife","adults","indoor","comedy"]),
    ("{city} Improv Show",             "entertainment",2.0, (20,  40), ["indoor","adults","comedy","entertainment"]),
    ("{city} Ghost Tour",              "entertainment",2.0, (25,  45), ["walking","adults","evening","entertainment"]),
    ("{city} Escape Room",             "entertainment",1.5, (28,  42), ["indoor","group","adults","entertainment"]),
    ("{city} Live Music Venue",        "nightlife",    2.5, (15,  45), ["music","adults","evening","nightlife"]),
    ("{city} Trivia Night",            "entertainment",2.0, (10,  25), ["indoor","adults","evening","group"]),
    ("Spa Day {city}",                 "wellness",     4.0, (80, 180), ["indoor","adults","relaxation","spa"]),
    ("{city} Yoga in the Park",        "wellness",     1.5, (0,   20), ["outdoor","morning","active","family"]),
    ("{city} Meditation Retreat",      "wellness",     3.0, (40,  90), ["indoor","adults","relaxation","wellness"]),
    ("{city} Science Center",          "culture",      3.0, (18,  32), ["indoor","family","education","science"]),
    ("{city} Planetarium Show",        "culture",      1.5, (12,  22), ["indoor","family","education","science"]),
    ("{city} Children's Museum",       "culture",      2.5, (10,  20), ["indoor","family","kids","education"]),
    ("Professional Sports Game {city}","entertainment",3.0, (40, 150), ["indoor","sports","adults","family"]),
    ("{city} Bowling Alley Night",     "entertainment",2.0, (20,  40), ["indoor","group","family","evening"]),
    ("{city} Mini Golf",               "entertainment",1.5, (12,  22), ["outdoor","family","active"]),
    ("{city} Photography Walk",        "culture",      2.5, (25,  55), ["outdoor","walking","art","adults"]),
    ("{city} Sunset Picnic Kit",       "nature",       2.0, (30,  55), ["outdoor","nature","family","romantic"]),
    ("{city} Paddleboarding",          "adventure",    2.0, (35,  65), ["water","outdoor","active","adventure"]),
    ("{city} Surfing Lesson",          "adventure",    2.5, (60, 110), ["water","outdoor","active","adventure"]),
    ("{city} Ziplining",               "adventure",    2.0, (50,  90), ["outdoor","active","adventure","adults"]),
    ("{city} Hot Air Balloon",         "adventure",    2.5, (150,280), ["aerial","outdoor","scenic","adults","romantic"]),
    ("{city} Distillery Tour",         "food",         2.0, (35,  65), ["food","adults","indoor"]),
    ("{city} Food Hall Crawl",         "food",         2.5, (20,  50), ["food","indoor","adults","family"]),
    ("{city} Night Market",            "food",         2.0, (15,  40), ["food","outdoor","evening","family"]),
    ("{city} Scenic Drive Tour",       "sightseeing",  3.0, (0,   35), ["outdoor","scenic","family"]),
    ("{city} Museum of Science",       "culture",      3.0, (18,  32), ["indoor","family","education","science"]),
]

VEGAN_RESTAURANTS = [
    "The Green Plate","Root & Branch","Plant Paradise","Harvest Table",
    "Verdant Kitchen","Pure Eats","The Sprout","Leafy Greens Cafe",
    "Planted","Nourish Bowl","Green Soul","Earthen Kitchen",
]

def rand_time(h_lo=5, h_hi=23):
    return time(random.randint(h_lo, h_hi),
                random.choice([0,5,10,15,20,25,30,35,40,45,50,55]))

def haversine_hours(iata1, iata2):
    r1 = AIRPORT_LOOKUP.get(iata1); r2 = AIRPORT_LOOKUP.get(iata2)
    if not r1 or not r2:
        return 3.0
    lat1,lon1 = math.radians(r1[4]), math.radians(r1[5])
    lat2,lon2 = math.radians(r2[4]), math.radians(r2[5])
    dlat,dlon = lat2-lat1, lon2-lon1
    a = math.sin(dlat/2)**2 + math.cos(lat1)*math.cos(lat2)*math.sin(dlon/2)**2
    miles = 3958.8 * 2 * math.asin(math.sqrt(a))
    return max(0.75, miles/500 + random.uniform(-0.1,0.3))

def time_add(t: time, hours: float) -> time:
    dt = datetime.combine(date.today(), t) + timedelta(hours=hours)
    return dt.time()

def fmt(t: time) -> str:
    return t.strftime("%H:%M")

if os.path.exists(args.db):
    os.remove(args.db)
conn = sqlite3.connect(args.db)
cur  = conn.cursor()

cur.executescript("""
PRAGMA journal_mode=WAL;

CREATE TABLE airports (
    iata TEXT PRIMARY KEY, city TEXT NOT NULL, state TEXT NOT NULL,
    tz_offset INTEGER NOT NULL, latitude REAL NOT NULL, longitude REAL NOT NULL
);
CREATE TABLE airlines (
    iata TEXT PRIMARY KEY, name TEXT NOT NULL,
    on_time_rate REAL NOT NULL, cancel_rate REAL NOT NULL
);
CREATE TABLE flights (
    flight_id      TEXT PRIMARY KEY,
    airline_iata   TEXT NOT NULL,
    flight_number  TEXT NOT NULL,
    origin         TEXT NOT NULL,
    destination    TEXT NOT NULL,
    depart_date    TEXT NOT NULL,
    depart_time    TEXT NOT NULL,
    arrive_time    TEXT NOT NULL,
    duration_hours REAL NOT NULL,
    price          REAL NOT NULL,
    seats_available INTEGER NOT NULL,
    stops          INTEGER NOT NULL,
    layover_airport TEXT,
    layover_minutes INTEGER,
    cabin          TEXT NOT NULL,
    FOREIGN KEY(airline_iata)   REFERENCES airlines(iata),
    FOREIGN KEY(origin)         REFERENCES airports(iata),
    FOREIGN KEY(destination)    REFERENCES airports(iata)
);
CREATE TABLE hotels (
    hotel_id        TEXT PRIMARY KEY,
    name            TEXT NOT NULL,
    city            TEXT NOT NULL,
    airport_iata    TEXT NOT NULL,
    brand           TEXT NOT NULL,
    tier            TEXT NOT NULL,
    price_per_night REAL NOT NULL,
    rating          REAL NOT NULL,
    num_reviews     INTEGER NOT NULL,
    amenities       TEXT NOT NULL,
    pet_friendly    INTEGER NOT NULL,
    accessible      INTEGER NOT NULL,
    vegan_options   INTEGER NOT NULL,
    distance_miles  REAL NOT NULL,
    max_guests      INTEGER NOT NULL,
    FOREIGN KEY(airport_iata) REFERENCES airports(iata)
);
CREATE TABLE hotel_availability (
    avail_id   INTEGER PRIMARY KEY AUTOINCREMENT,
    hotel_id   TEXT NOT NULL,
    check_in   TEXT NOT NULL,
    check_out  TEXT NOT NULL,
    rooms_left INTEGER NOT NULL,
    FOREIGN KEY(hotel_id) REFERENCES hotels(hotel_id)
);
CREATE TABLE activities (
    activity_id    TEXT PRIMARY KEY,
    name           TEXT NOT NULL,
    city           TEXT NOT NULL,
    airport_iata   TEXT NOT NULL,
    category       TEXT NOT NULL,
    description    TEXT NOT NULL,
    duration_hrs   REAL NOT NULL,
    cost           REAL NOT NULL,
    rating         REAL NOT NULL,
    open_time      TEXT NOT NULL,
    close_time     TEXT NOT NULL,
    days_open      TEXT NOT NULL,
    tags           TEXT NOT NULL,
    max_group      INTEGER NOT NULL,
    accessible     INTEGER NOT NULL,
    vegan_friendly INTEGER NOT NULL,
    FOREIGN KEY(airport_iata) REFERENCES airports(iata)
);
CREATE INDEX idx_fl_route ON flights(origin,destination,depart_date,cabin);
CREATE INDEX idx_ht_city  ON hotels(airport_iata,tier);
CREATE INDEX idx_ac_city  ON activities(airport_iata,category);
""")
conn.commit()

cur.executemany("INSERT INTO airports VALUES (?,?,?,?,?,?)", AIRPORTS)
cur.executemany("INSERT INTO airlines VALUES (?,?,?,?)", AIRLINES)
conn.commit()

print("Generating flights...")

DATE_START = date(2025,6,1)
DATE_END   = date(2025,8,31)
fid = 1
flight_rows = []

iatas = [a[0] for a in AIRPORTS]
pairs = [(o,d) for o in iatas for d in iatas if o != d]

for origin, dest in pairs:
    dur_base = haversine_hours(origin, dest)
    n_dates  = random.randint(35, 55)
    date_pool = list({DATE_START + timedelta(days=random.randint(0,(DATE_END-DATE_START).days))
                      for _ in range(n_dates)})
    for fl_date in date_pool:
        for _ in range(random.randint(1,4)):
            airline  = random.choice(AIRLINES)
            cabin    = random.choices(["economy","business"],[0.87,0.13])[0]
            dur      = round(dur_base + random.uniform(-0.1,0.4), 2)
            base     = dur * random.uniform(50,115)
            if cabin == "business":      base *= random.uniform(2.5,4.0)
            if fl_date.month in (6,7,8): base *= random.uniform(1.1,1.35)
            price    = round(max(39.0, base + random.uniform(-20,40)), 2)
            dep      = rand_time(5,22)
            arr      = time_add(dep, dur)
            stops    = random.choices([0,1],[0.62,0.38])[0]
            lay_ap   = random.choice([a for a in iatas if a not in (origin,dest)]) if stops else None
            lay_min  = random.randint(45,180) if stops else None
            flight_rows.append((
                f"FL{fid:07d}", airline[0], f"{airline[0]}{random.randint(100,9999)}",
                origin, dest, fl_date.isoformat(), fmt(dep), fmt(arr),
                dur, price, random.randint(1,140), stops, lay_ap, lay_min, cabin
            ))
            fid += 1

cur.executemany("INSERT INTO flights VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)", flight_rows)
conn.commit()
print(f"  → {len(flight_rows):,} flight records")

print("Generating hotels...")

hotel_rows = []
avail_rows = []
hid = 1

for iata, city, state, *_ in AIRPORTS:
    n_hotels = random.randint(18, 28)
    for _ in range(n_hotels):
        brand, tier, price_range, amenities = random.choice(HOTEL_CHAINS)
        price  = round(random.uniform(*price_range), 2)
        if tier == "luxury":
            rating = round(random.uniform(4.0,5.0),1)
        elif tier == "upscale":
            rating = round(random.uniform(3.8,4.9),1)
        elif tier == "midscale":
            rating = round(random.uniform(3.2,4.5),1)
        else:
            rating = round(random.uniform(2.5,4.0),1)

        name = (f"{brand} {city}" if random.random()>0.3
                else random.choice([f"The {city} {brand}",
                                    f"{city} Grand {brand}",
                                    f"Hotel {random.randint(1,999)} {city}"]))
        pet  = int(random.random()<0.45)
        acc  = int(random.random()<0.80)
        veg  = int("restaurant" in amenities and random.random()<0.40)
        dist = round(random.uniform(0.3,20.0),1)
        guests = random.randint(1,6)

        hotel_rows.append((
            f"HT{hid:05d}", name, city, iata, brand, tier,
            price, rating, random.randint(30,8000),
            json.dumps(amenities), pet, acc, veg, dist, guests
        ))

        d = DATE_START
        while d < DATE_END:
            nights = random.randint(1,8)
            cout   = d + timedelta(days=nights)
            rooms  = random.choices([0,1,2,3,4,5,6,7,8,10],
                                    [5,5,10,15,20,15,10,10,5,5])[0]
            avail_rows.append((f"HT{hid:05d}", d.isoformat(), cout.isoformat(), rooms))
            d = cout
        hid += 1

cur.executemany("INSERT INTO hotels VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)", hotel_rows)
cur.executemany("INSERT INTO hotel_availability (hotel_id,check_in,check_out,rooms_left) VALUES (?,?,?,?)", avail_rows)
conn.commit()
print(f"  → {len(hotel_rows):,} hotel records, {len(avail_rows):,} availability windows")

print("Generating activities...")

act_rows = []
aid_counter = 1
WEEKDAYS = ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"]

for iata, city, state, *_ in AIRPORTS:
    for tmpl, category, duration, cost_range, tags in ACTIVITY_TEMPLATES:
        name = tmpl.format(city=city)
        if category == "nightlife":
            open_h, close_h = "18:00", "02:00"
        elif "morning" in tags:
            open_h, close_h = "07:00", "13:00"
        elif "outdoor" in tags:
            open_h, close_h = "08:00", "19:00"
        else:
            open_h  = f"{random.randint(9,11):02d}:00"
            close_h = f"{random.randint(17,21):02d}:00"

        days   = WEEKDAYS[:] if category != "nightlife" else random.sample(WEEKDAYS, random.randint(4,7))
        cost   = round(random.uniform(*cost_range), 2)
        rating = round(random.uniform(3.4,5.0),1)
        veg_f  = int("vegan" in tags or ("food" in tags and random.random()<0.35))
        acc    = int(random.random()<0.70)

        act_rows.append((
            f"AC{aid_counter:06d}", name, city, iata, category,
            f"A popular {category} experience in {city}, {state}.",
            duration, cost, rating,
            open_h, close_h,
            json.dumps(sorted(days)),
            json.dumps(tags),
            random.randint(1,60), acc, veg_f
        ))
        aid_counter += 1

    for vr in random.sample(VEGAN_RESTAURANTS, 3):
        act_rows.append((
            f"AC{aid_counter:06d}", f"{vr} {city}", city, iata,
            "food", f"Vegan restaurant in {city}.",
            1.5, round(random.uniform(15,45),2),
            round(random.uniform(4.0,5.0),1),
            "11:00","21:00",
            json.dumps(WEEKDAYS),
            json.dumps(["food","vegan","indoor","adults","family"]),
            30, 1, 1
        ))
        aid_counter += 1

cur.executemany("INSERT INTO activities VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)", act_rows)
conn.commit()
print(f"  → {len(act_rows):,} activity records")

print("Exporting CSVs...")
TABLES = ["airports","airlines","flights","hotels","hotel_availability","activities"]
for tbl in TABLES:
    rows = conn.execute(f"SELECT * FROM {tbl}").fetchall()
    cols = [d[0] for d in conn.execute(f"SELECT * FROM {tbl} LIMIT 0").description]
    path = os.path.join(args.csv_dir, f"{tbl}.csv")
    with open(path,"w",newline="",encoding="utf-8") as f:
        w=csv.writer(f); w.writerow(cols); w.writerows(rows)
    print(f"  → {path}  ({len(rows):,} rows)")

conn.close()
print("\n✅ Done!")
print(f"   DB : {args.db}")
print(f"   CSV: {args.csv_dir}/")
